// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmOXkLV7nc59JTbJ03EcSWFVw5OGyr4PY',
    appId: '1:623338569626:web:24496d400257efa6120423',
    messagingSenderId: '623338569626',
    projectId: 'zporter-board',
    authDomain: 'zporter-board.firebaseapp.com',
    storageBucket: 'zporter-board.firebasestorage.app',
    measurementId: 'G-RNFGQC4KPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiXs0KM7tNLjAB9UVKb-D1DDevaASEaRQ',
    appId: '1:623338569626:android:7ccaf1f6ec4ab51b120423',
    messagingSenderId: '623338569626',
    projectId: 'zporter-board',
    storageBucket: 'zporter-board.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMIAOYa-sqbdLTCYhp3YucRloN_Lur0jE',
    appId: '1:623338569626:ios:1b10755070663085120423',
    messagingSenderId: '623338569626',
    projectId: 'zporter-board',
    storageBucket: 'zporter-board.firebasestorage.app',
    iosBundleId: 'com.zporter.zporterBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMIAOYa-sqbdLTCYhp3YucRloN_Lur0jE',
    appId: '1:623338569626:ios:1b10755070663085120423',
    messagingSenderId: '623338569626',
    projectId: 'zporter-board',
    storageBucket: 'zporter-board.firebasestorage.app',
    iosBundleId: 'com.zporter.zporterBoard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmOXkLV7nc59JTbJ03EcSWFVw5OGyr4PY',
    appId: '1:623338569626:web:22295fb13fa3f8ca120423',
    messagingSenderId: '623338569626',
    projectId: 'zporter-board',
    authDomain: 'zporter-board.firebaseapp.com',
    storageBucket: 'zporter-board.firebasestorage.app',
    measurementId: 'G-0Y2N6WZFL6',
  );
}
